version: '3.8'
services:
  server:
    image: ecommerce_server:latest
    env_file:
      - ${SECRET}
    networks:
      - default
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
      placement:
        constraints: [node.hostname == glud.udistrital.edu.co]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=reverse_proxy"
        - "traefik.http.routers.ecommerce.entrypoints=websecure"
        - "traefik.http.routers.ecommerce.rule=Host(`lgsus.glud.org`)"
        - "traefik.http.routers.ecommerce.service=ecommerce"
        - "traefik.http.services.ecommerce.loadbalancer.server.port=${PORT}"
    depends_on: 
      - database
          
  database:
    image: postgres:latest
    networks:
      - default
    env_file:
      - ${SECRET}
    volumes:
      - data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
    depends_on: 
      - default
volumes:
  data:

networks:
  reverse_proxy:
    external: true