version: '3.8'
services:
  server:
    image: ecommerce_server:latest
    env_file:
      - ${SECRET}
    networks:
      - default
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
    depends_on: 
      - database
          
  database:
    image: postgres:latest
    networks:
      - default
    env_file:
      - ${SECRET}
    volumes:
      - data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
volumes:
  data:

networks:
  reverse_proxy:
    external: true