version: '3.8'
services:
  server:
    image: ecommerce_server:latest
    env_file:
      - .env
    networks:
      - default
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
    depends_on: 
      - database
          
  database:
    image: postgres:latest
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
    depends_on: 
      - default
volumes:
  data:
